# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration
client_id = "07dc716bc6623c8daecb0e8e2bf8ef3c"
name = "TrustShield Trust Badges"
application_url = "https://trustshield-trust-badges-production.up.railway.app"
embedded = true

[access_scopes]
scopes = "read_themes,write_themes,read_products"

[auth]
redirect_urls = [ "https://trustshield-trust-badges-production.up.railway.app/auth/callback", "https://trustshield-trust-badges-production.up.railway.app/auth/login/callback" ]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["app_subscriptions/update"]
  uri = "/webhooks"

  [webhooks.privacy_compliance]
  customer_data_request_url = "https://trustshield-trust-badges-production.up.railway.app/webhooks"
  customer_deletion_url = "https://trustshield-trust-badges-production.up.railway.app/webhooks"
  shop_deletion_url = "https://trustshield-trust-badges-production.up.railway.app/webhooks"

[app_store]
privacy_policy_url = "https://trustshield-trust-badges-production.up.railway.app/app/privacy"
terms_of_service_url = "https://trustshield-trust-badges-production.up.railway.app/app/terms"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "trustshield-test-store.myshopify.com"
